export const  AUTH_REQUEST = 'AUTH_REQUEST'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const  AUTH_FAIL = 'AUTH_FAIL'
export const CLEAR_ERROR = 'CLEAR_ERROR'

export const FACEBOOK_ADS_REQUEST = 'FACEBOOK_ADS_REQUEST';
export const FACEBOOK_ADS_SUCCESS = 'FACEBOOK_ADS_SUCCESS';
export const FACEBOOK_ADS_FAIL = 'FACEBOOK_ADS_FAIL';

export const GOOGLE_ADS_REQUEST = 'GOOGLE_ADS_REQUEST';
export const GOOGLE_ADS_SUCCESS = 'GOOGLE_ADS_SUCCESS';
export const GOOGLE_ADS_FAIL = 'GOOGLE_ADS_FAIL';
